/**
 * ManageSpace Lease API
 * ManageSpace Lease API Documentation
 *
 * The version of the OpenAPI document: 0.0.11-dev
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { CreateReservationBatchRequest } from './createReservationBatchRequest';

export class CreateReservationsRequest {
    /**
    * Reservations
    */
    'reservations': Array<CreateReservationBatchRequest>;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "reservations",
            "baseName": "reservations",
            "type": "Array<CreateReservationBatchRequest>"
        }    ];

    static getAttributeTypeMap() {
        return CreateReservationsRequest.attributeTypeMap;
    }
}

