/**
 * ManageSpace Lease API
 * ManageSpace Lease API Documentation
 *
 * The version of the OpenAPI document: 0.0.11-dev
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

export class RentalAgreementResponse {
    /**
    * Rental agreement ID
    */
    'rentalAgreementId': string;
    /**
    * Account ID
    */
    'accountId': string;
    /**
    * Account full name.
    */
    'accountName': string;
    /**
    * Document ID
    */
    'documentId': string;
    /**
    * Org ID
    */
    'orgId': string;
    /**
    * Created by
    */
    'createdBy': string;
    /**
    * Updated by
    */
    'updatedBy': string | null;
    /**
    * Created at.
    */
    'createdAt': string;
    /**
    * Updated at.
    */
    'updatedAt'?: string | null;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "rentalAgreementId",
            "baseName": "rentalAgreementId",
            "type": "string"
        },
        {
            "name": "accountId",
            "baseName": "accountId",
            "type": "string"
        },
        {
            "name": "accountName",
            "baseName": "accountName",
            "type": "string"
        },
        {
            "name": "documentId",
            "baseName": "documentId",
            "type": "string"
        },
        {
            "name": "orgId",
            "baseName": "orgId",
            "type": "string"
        },
        {
            "name": "createdBy",
            "baseName": "createdBy",
            "type": "string"
        },
        {
            "name": "updatedBy",
            "baseName": "updatedBy",
            "type": "string"
        },
        {
            "name": "createdAt",
            "baseName": "createdAt",
            "type": "string"
        },
        {
            "name": "updatedAt",
            "baseName": "updatedAt",
            "type": "string"
        }    ];

    static getAttributeTypeMap() {
        return RentalAgreementResponse.attributeTypeMap;
    }
}

