/**
 * ManageSpace Lease API
 * ManageSpace Lease API Documentation
 *
 * The version of the OpenAPI document: 0.0.12-dev
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

export class ReservationStatus {
    /**
    * Status ID
    */
    'statusId': number;
    /**
    * Status Name
    */
    'statusName': string;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "statusId",
            "baseName": "statusId",
            "type": "number"
        },
        {
            "name": "statusName",
            "baseName": "statusName",
            "type": "string"
        }    ];

    static getAttributeTypeMap() {
        return ReservationStatus.attributeTypeMap;
    }
}

