/**
 * ManageSpace Lease API
 * ManageSpace Lease API Documentation
 *
 * The version of the OpenAPI document: 0.0.12-dev
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { ReservationStatus } from './reservationStatus';

export class ReservationResponse {
    /**
    * Reservation ID
    */
    'reservationId': string;
    /**
    * Unit ID
    */
    'unitId': string;
    /**
    * Unit Name
    */
    'unitName': string;
    /**
    * Site ID
    */
    'siteId': string;
    /**
    * Organization ID
    */
    'orgId': string;
    /**
    * Account ID
    */
    'accountId': string;
    /**
    * Account Name
    */
    'accountName': string;
    /**
    * Account Email Address
    */
    'email': string | null;
    /**
    * Account Mobile Number
    */
    'mobileNumber': string;
    /**
    * Reservation Notes
    */
    'notes'?: string | null;
    /**
    * Expires At
    */
    'expiresAt': Date;
    /**
    * Created date
    */
    'createdAt': Date | null;
    'status': ReservationStatus;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "reservationId",
            "baseName": "reservationId",
            "type": "string"
        },
        {
            "name": "unitId",
            "baseName": "unitId",
            "type": "string"
        },
        {
            "name": "unitName",
            "baseName": "unitName",
            "type": "string"
        },
        {
            "name": "siteId",
            "baseName": "siteId",
            "type": "string"
        },
        {
            "name": "orgId",
            "baseName": "orgId",
            "type": "string"
        },
        {
            "name": "accountId",
            "baseName": "accountId",
            "type": "string"
        },
        {
            "name": "accountName",
            "baseName": "accountName",
            "type": "string"
        },
        {
            "name": "email",
            "baseName": "email",
            "type": "string"
        },
        {
            "name": "mobileNumber",
            "baseName": "mobileNumber",
            "type": "string"
        },
        {
            "name": "notes",
            "baseName": "notes",
            "type": "string"
        },
        {
            "name": "expiresAt",
            "baseName": "expiresAt",
            "type": "Date"
        },
        {
            "name": "createdAt",
            "baseName": "createdAt",
            "type": "Date"
        },
        {
            "name": "status",
            "baseName": "status",
            "type": "ReservationStatus"
        }    ];

    static getAttributeTypeMap() {
        return ReservationResponse.attributeTypeMap;
    }
}

