/**
 * ManageSpace Lease API
 * ManageSpace Lease API Documentation
 *
 * The version of the OpenAPI document: 0.0.12-dev
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { AccountStatsSpaceReservation } from './accountStatsSpaceReservation';

export class SpaceReservationGroupedResponse {
    /**
    * Grouped by facet, ex: `10x10`
    */
    'groupedByFacet': string;
    /**
    * The count of reserved unit spaces.
    */
    'reservedCount': number;
    /**
    * List of accounts
    */
    'accounts': Array<AccountStatsSpaceReservation>;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "groupedByFacet",
            "baseName": "groupedByFacet",
            "type": "string"
        },
        {
            "name": "reservedCount",
            "baseName": "reservedCount",
            "type": "number"
        },
        {
            "name": "accounts",
            "baseName": "accounts",
            "type": "Array<AccountStatsSpaceReservation>"
        }    ];

    static getAttributeTypeMap() {
        return SpaceReservationGroupedResponse.attributeTypeMap;
    }
}

