/**
 * ManageSpace Lease API
 * ManageSpace Lease API Documentation
 *
 * The version of the OpenAPI document: 0.0.11-dev
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { Lease } from './lease';
import { SubscriptionStatusResponse } from './subscriptionStatusResponse';

export class SubscriptionResponse {
    /**
    * Subscription ID
    */
    'subscriptionId': string;
    /**
    * Amount of the subscription
    */
    'amount': number;
    /**
    * Currency of the subscription amount
    */
    'currency': string;
    /**
    * Subscription start date
    */
    'startDate': Date;
    /**
    * Billing cycle anchor date
    */
    'billingCycleAnchor': Date;
    /**
    * Subscription fee percent
    */
    'feePercent': number;
    'subscriptionStatus': SubscriptionStatusResponse;
    'lease': Lease;
    /**
    * Payment provider id
    */
    'paymentProviderId': string;
    /**
    * Billing cycle anchor date
    */
    'paymentProviderBillingCycleAnchor': Date;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "subscriptionId",
            "baseName": "subscriptionId",
            "type": "string"
        },
        {
            "name": "amount",
            "baseName": "amount",
            "type": "number"
        },
        {
            "name": "currency",
            "baseName": "currency",
            "type": "string"
        },
        {
            "name": "startDate",
            "baseName": "startDate",
            "type": "Date"
        },
        {
            "name": "billingCycleAnchor",
            "baseName": "billingCycleAnchor",
            "type": "Date"
        },
        {
            "name": "feePercent",
            "baseName": "feePercent",
            "type": "number"
        },
        {
            "name": "subscriptionStatus",
            "baseName": "subscriptionStatus",
            "type": "SubscriptionStatusResponse"
        },
        {
            "name": "lease",
            "baseName": "lease",
            "type": "Lease"
        },
        {
            "name": "paymentProviderId",
            "baseName": "paymentProviderId",
            "type": "string"
        },
        {
            "name": "paymentProviderBillingCycleAnchor",
            "baseName": "paymentProviderBillingCycleAnchor",
            "type": "Date"
        }    ];

    static getAttributeTypeMap() {
        return SubscriptionResponse.attributeTypeMap;
    }
}

