/**
 * ManageSpace Lease API
 * ManageSpace Lease API Documentation
 *
 * The version of the OpenAPI document: 0.0.11-dev
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

export class SubscriptionStatusResponse {
    /**
    * Subscription Status ID
    */
    'subscriptionStatusId': number;
    /**
    * Subscription Status display name
    */
    'displayName': string;
    /**
    * Subscription Status code name
    */
    'codeName': string;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "subscriptionStatusId",
            "baseName": "subscriptionStatusId",
            "type": "number"
        },
        {
            "name": "displayName",
            "baseName": "displayName",
            "type": "string"
        },
        {
            "name": "codeName",
            "baseName": "codeName",
            "type": "string"
        }    ];

    static getAttributeTypeMap() {
        return SubscriptionStatusResponse.attributeTypeMap;
    }
}

