/**
 * ManageSpace Lease API
 * ManageSpace Lease API Documentation
 *
 * The version of the OpenAPI document: 0.0.12-dev
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

export class UpdateRentalIntendedMoveOutDateRequest {
    /**
    * Move Out Date
    */
    'intendedMoveOutDate': Date;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "intendedMoveOutDate",
            "baseName": "intendedMoveOutDate",
            "type": "Date"
        }    ];

    static getAttributeTypeMap() {
        return UpdateRentalIntendedMoveOutDateRequest.attributeTypeMap;
    }
}

