/**
 * ManageSpace Lease API
 * ManageSpace Lease API Documentation
 *
 * The version of the OpenAPI document: 0.0.11-dev
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

export class UpdateReservationRequest {
    /**
    * Account ID
    */
    'accountId': string;
    /**
    * Reservation Notes
    */
    'notes': string | null;
    /**
    * Expires At
    */
    'expiresAt'?: Date | null;
    /**
    * Status
    */
    'statusId': number;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "accountId",
            "baseName": "accountId",
            "type": "string"
        },
        {
            "name": "notes",
            "baseName": "notes",
            "type": "string"
        },
        {
            "name": "expiresAt",
            "baseName": "expiresAt",
            "type": "Date"
        },
        {
            "name": "statusId",
            "baseName": "statusId",
            "type": "number"
        }    ];

    static getAttributeTypeMap() {
        return UpdateReservationRequest.attributeTypeMap;
    }
}

